version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Build Static App
          command: npm run export

      - run:
          name: Run Tests
          command:  echo "no tests"

      - run:
          name: Deploy to Webserver
          command: scp -o StrictHostKeyChecking=no -r _static/* circleci@next.pow.co:/opt/next.pow.co

