version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
      - build_docker

jobs:
  build_docker:
      docker:
        - image: circleci/node:14
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build docker image
            command: docker build -t $DOCKER_REPO:$CIRCLE_BRANCH . 
        - run:
            name: Push to Docker Hub
            command: |
              docker login --username $DOCKER_USER --password $DOCKER_PASSWORD 
              docker push $DOCKER_REPO:$CIRCLE_BRANCH


  build_and_deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Build Static App
          command: npm run export

      - run:
          name: Run Tests
          command:  echo "no tests"

      - run:
          name: Deploy to Webserver
          command: scp -o StrictHostKeyChecking=no -r _static/* circleci@next.pow.co:/opt/next.pow.co

